---
language: ruby

sudo: required

services:
  - docker

env:
  - VERSION=1.0.2

install:
  - docker build -t lgatica/pgrestore-s3:latest -t lgatica/pgrestore-s3:${TRAVIS_TAG:-$VERSION} .

script:
  - docker run --rm lgatica/pgrestore-s3:${TRAVIS_TAG:-$VERSION} pg_restore --version

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push lgatica/mongorestore-s3
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
